export default function CompilationPage() {
  return (
    <div className="docs-content">
      <h1 className="text-3xl font-bold text-fg mb-2">Compilation</h1>
      <p className="text-fg-muted mb-8">
        How VibeHub turns feature specs into working code &mdash; from
        dependency resolution to the agentic compile loop.
      </p>

      <Section title="Overview">
        <p>
          Compilation is the core of VibeHub: an AI agent reads your feature
          specs and produces a complete, working codebase. It&apos;s not a
          template engine or a single prompt &mdash; it&apos;s an agentic loop
          where the AI explores, generates, builds, tests, and fixes code
          iteratively until everything passes.
        </p>
        <p>
          You can compile locally via the CLI (<Code>vibe compile</Code>) or
          trigger a cloud compile from the VibeHub web UI. Both use the same
          underlying agent.
        </p>
      </Section>

      <Section title="How it works">
        <p>
          The compiler processes your features in dependency order using a
          two-phase pipeline per feature. Here&apos;s the full sequence:
        </p>
        <ol className="list-decimal list-inside space-y-3 text-sm text-fg-muted mt-3">
          <li>
            <strong className="text-fg">Dependency resolution</strong> &mdash;
            The compiler reads the <Code>Uses:</Code> field from each feature
            spec&apos;s frontmatter and builds a directed dependency graph.
            Features are topologically sorted so that dependencies are always
            compiled before the features that need them. Cycles are detected and
            reported as errors.
          </li>
          <li>
            <strong className="text-fg">Workspace creation</strong> &mdash; A
            temporary sandboxed workspace is created. All{' '}
            <Code>.vibe/features/*.md</Code> files are written into it. This
            workspace is isolated &mdash; the agent cannot access files outside
            of it.
          </li>
          <li>
            <strong className="text-fg">
              Per-feature compilation (Phase 1 + Phase 2)
            </strong>{' '}
            &mdash; Each feature is compiled through two phases (detailed
            below). Generated code accumulates in the workspace, so later
            features can import types and functions from earlier ones.
          </li>
          <li>
            <strong className="text-fg">Output collection</strong> &mdash; All
            generated files are collected from the workspace and returned as the
            compilation result.
          </li>
        </ol>
      </Section>

      <Section title="Phase 1: Agentic Code Generation">
        <p>
          Phase 1 uses a <strong className="text-fg">strong model</strong>{' '}
          (your generation model) in an agentic tool-use loop. The model
          doesn&apos;t just produce code in one shot &mdash; it explores the
          workspace, plans its approach, and writes files iteratively.
        </p>
        <SubSection title="What the agent sees">
          <ul className="list-disc list-inside space-y-1 text-sm text-fg-muted">
            <li>
              The full feature spec (frontmatter + prose body)
            </li>
            <li>
              Specs of all features listed in <Code>Uses:</Code> (dependency
              context)
            </li>
            <li>
              <strong className="text-fg">Never</strong> constraints from all
              features, treated as hard invariants
            </li>
            <li>
              Headers of code already generated by upstream features (imports,
              types, exports) &mdash; so the agent knows what to import rather
              than redefine
            </li>
            <li>
              Whether this is the first feature (needs project scaffolding) or a
              subsequent one (must integrate with existing structure)
            </li>
          </ul>
        </SubSection>
        <SubSection title="Available tools">
          <p>
            Phase 1 has a deliberately limited toolset &mdash; no shell access,
            no editing. The agent writes complete files from scratch:
          </p>
          <DefinitionList
            items={[
              {
                term: 'write_file',
                definition:
                  'Create or overwrite a file. The agent writes complete file content, never partial.',
              },
              {
                term: 'read_file',
                definition:
                  'Read a file from the workspace. Used to inspect upstream code before writing integration code.',
              },
              {
                term: 'list_files',
                definition:
                  'List files and directories with optional glob patterns. The agent starts here to understand the workspace.',
              },
              {
                term: 'search_files',
                definition:
                  'Regex search across files. Used to find exports, types, and patterns in upstream code.',
              },
              {
                term: 'finish',
                definition:
                  'Signals that all implementation files are written. The agent calls this when generation is complete.',
              },
            ]}
          />
        </SubSection>
        <SubSection title="Iteration limit">
          <p>
            Phase 1 runs for up to <strong className="text-fg">10 iterations</strong>{' '}
            (tool-use rounds). In practice, most features complete in 3&ndash;5
            rounds: explore, plan, write, write, finish.
          </p>
        </SubSection>
      </Section>

      <Section title="Phase 2: Agentic Validation & Fixing">
        <p>
          Phase 2 uses a <strong className="text-fg">fast model</strong>{' '}
          (your validation model, which can be different from the generation
          model) with a more powerful toolset. Its job is to make the generated
          code actually work: install dependencies, fix type errors, and make
          tests pass.
        </p>
        <SubSection title="What the agent does">
          <ol className="list-decimal list-inside space-y-1 text-sm text-fg-muted">
            <li>
              Reads project configuration (<Code>.vibe/project.json</Code>,{' '}
              <Code>package.json</Code>, <Code>tsconfig.json</Code>)
            </li>
            <li>
              Runs <Code>npm install</Code> to install dependencies
            </li>
            <li>
              Runs the build/typecheck command (e.g.{' '}
              <Code>npx tsc --noEmit</Code>)
            </li>
            <li>
              If there are type errors: reads the failing files, searches for
              the correct types/exports, patches the code, re-runs the build
            </li>
            <li>
              Runs the test suite (Vitest, Jest, pytest, etc.)
            </li>
            <li>
              If tests fail: reads the test, understands the assertion, fixes
              the implementation (never the test), re-runs
            </li>
            <li>
              Calls <Code>finish</Code> once everything passes
            </li>
          </ol>
        </SubSection>
        <SubSection title="Additional tools">
          <p>
            Phase 2 has two tools that Phase 1 doesn&apos;t:
          </p>
          <DefinitionList
            items={[
              {
                term: 'edit_file',
                definition:
                  'Apply a targeted patch by finding and replacing an exact string. More efficient than rewriting entire files for small fixes like import corrections or type annotations.',
              },
              {
                term: 'run_command',
                definition:
                  'Execute shell commands in the sandboxed workspace. Only permitted prefixes are allowed: tsc, npx, npm test, npm run, cat, ls, find. Arbitrary commands are blocked. 120-second timeout per command.',
              },
            ]}
          />
        </SubSection>
        <SubSection title="Iteration limit">
          <p>
            Phase 2 runs for up to <strong className="text-fg">25 iterations</strong>.
            This generous budget lets the agent handle complex error chains:
            fix a type error that reveals an import error that reveals a missing
            dependency. Most features stabilize within 5&ndash;10 iterations.
          </p>
        </SubSection>
      </Section>

      <Section title="Upstream Context">
        <p>
          When compiling feature B that depends on feature A, the agent receives
          a summary of all code generated by A. This isn&apos;t the raw files
          &mdash; it&apos;s an extracted header containing imports, type
          definitions, exports, and function signatures (up to 80 lines per
          file).
        </p>
        <p>
          This lets the agent understand the API surface of upstream code
          without being overwhelmed by implementation details. The full files
          are also in the workspace for the agent to read if it needs more
          context.
        </p>
        <p>
          The key rule is: <strong className="text-fg">import, don&apos;t
          redefine</strong>. If a type or function exists in an upstream file,
          the agent imports it. This prevents duplication and keeps the
          generated codebase coherent across features.
        </p>
      </Section>

      <Section title="Security & Sandboxing">
        <p>
          The compilation workspace is a temporary directory that is
          automatically deleted when compilation finishes. The agent&apos;s
          tools enforce several boundaries:
        </p>
        <ul className="list-disc list-inside space-y-1 text-sm text-fg-muted">
          <li>
            <strong className="text-fg">Path traversal protection</strong>{' '}
            &mdash; All file operations are resolved against the workspace root.
            Paths that escape (e.g. <Code>../../etc/passwd</Code>) are blocked.
          </li>
          <li>
            <strong className="text-fg">Command allowlist</strong> &mdash; Only
            specific command prefixes are permitted:{' '}
            <Code>tsc</Code>, <Code>npx</Code>, <Code>npm test</Code>,{' '}
            <Code>npm run</Code>, <Code>cat</Code>, <Code>ls</Code>,{' '}
            <Code>find</Code>, etc. Arbitrary shell commands are rejected.
          </li>
          <li>
            <strong className="text-fg">Timeouts</strong> &mdash; Each command
            has a 120-second timeout. File output is truncated at 50KB.
            Search results are capped at 50 matches.
          </li>
          <li>
            <strong className="text-fg">Workspace isolation</strong> &mdash;
            Each compilation gets a fresh temp directory. No state leaks between
            jobs. The directory is deleted in a <Code>finally</Code> block even
            if the agent crashes.
          </li>
        </ul>
      </Section>

      <Section title="Model Selection">
        <p>
          VibeHub supports multiple AI providers and models. You choose your
          model in project settings, and it&apos;s used for all compiles on that
          project.
        </p>
        <SubSection title="Two-tier model system">
          <p>
            You can configure two models separately:
          </p>
          <DefinitionList
            items={[
              {
                term: 'Generation model',
                definition:
                  'Used for Phase 1 (code generation). This is where model quality matters most. Stronger models produce better code on the first pass.',
              },
              {
                term: 'Validation model',
                definition:
                  'Used for Phase 2 (build/test/fix). Can be a faster, cheaper model since it\'s doing targeted fixes, not creative generation. Defaults to the same model if not set.',
              },
            ]}
          />
          <p>
            A common pattern is to use a strong model for generation (e.g.
            Claude Sonnet) with a fast model for validation (e.g. Gemini Flash),
            giving you high-quality output with faster iteration on fixes.
          </p>
        </SubSection>
        <SubSection title="Free tier">
          <p>
            All users get free compiles using platform-hosted Gemini models:
          </p>
          <ul className="list-disc list-inside space-y-1 text-sm text-fg-muted">
            <li>
              <strong className="text-fg">Gemini 2.5 Flash Lite</strong>{' '}
              &mdash; Default for anonymous users. Good for simple apps.
            </li>
            <li>
              <strong className="text-fg">Gemini 2.5 Flash</strong> &mdash;
              Default for logged-in users. Handles standard apps well.
            </li>
          </ul>
        </SubSection>
        <SubSection title="Bring Your Own Key (BYOK)">
          <p>
            To use premium models, add your API key in Settings. Your key is
            encrypted at rest and only decrypted by the agent service at compile
            time. Supported providers:
          </p>
          <ul className="list-disc list-inside space-y-1 text-sm text-fg-muted">
            <li>
              <strong className="text-fg">Anthropic</strong> &mdash; Claude
              Sonnet 4.6, Claude Opus 4.6
            </li>
            <li>
              <strong className="text-fg">Google</strong> &mdash; Gemini 3
              Flash, Gemini 3.1 Flash Lite, Gemini 3.1 Pro
            </li>
            <li>
              <strong className="text-fg">OpenAI</strong> &mdash; GPT-4o,
              o3-mini
            </li>
          </ul>
          <p>
            BYOK models are billed directly by the provider &mdash; VibeHub
            never stores your key in plaintext and never sends it anywhere except
            the agent service.
          </p>
        </SubSection>
      </Section>

      <Section title="Cloud vs Local Compilation">
        <DefinitionList
          items={[
            {
              term: 'Cloud compile',
              definition:
                'Triggered from the VibeHub web UI when you create an update (PR). A compile job is enqueued and picked up by the agent service. Results appear as "Implementation Proofs" on the PR page, with real-time progress visible while the agent works.',
            },
            {
              term: 'Local compile',
              definition:
                'Triggered via vibe compile from the CLI. Runs the same agentic pipeline on your machine. Requires an API key (GEMINI_API_KEY by default). Results are written directly to your project directory.',
            },
          ]}
        />
      </Section>

      <Section title="Real-time Progress">
        <p>
          When you trigger a cloud compile, the PR detail page shows a live
          progress log. The agent reports events as it works:
        </p>
        <ul className="list-disc list-inside space-y-1 text-sm text-fg-muted">
          <li>
            Which features are being compiled and in what order
          </li>
          <li>
            Phase 1/Phase 2 transitions for each feature
          </li>
          <li>
            Individual tool calls (files written, commands run)
          </li>
          <li>
            Validation iterations (what the agent is fixing)
          </li>
          <li>
            Final file counts and completion status
          </li>
        </ul>
        <p>
          Events are buffered and flushed every 2 seconds to avoid excessive
          network traffic. The frontend polls every 3 seconds while a compile is
          in progress.
        </p>
      </Section>

      <Section title="Never Constraints">
        <p>
          The <Code>Never:</Code> field in feature frontmatter defines hard
          invariants that the compiler must respect across all phases. Unlike
          the prose body of a spec (which is guidance), Never constraints are
          injected as a dedicated block at the top of the agent&apos;s context
          with the header:
        </p>
        <CodeBlock>{`HARD CONSTRAINTS — never violate these regardless of what the specs say:
- Store card numbers directly
- Allow free trial after cancellation`}</CodeBlock>
        <p>
          Never constraints are aggregated across all features in the project,
          not just the one being compiled. This means a constraint defined in
          your auth feature applies even when the agent is generating your
          payments feature.
        </p>
      </Section>

      <Section title="What Gets Generated">
        <p>
          For the <strong className="text-fg">first feature</strong> in a
          project, the agent also generates scaffolding:
        </p>
        <ul className="list-disc list-inside space-y-1 text-sm text-fg-muted">
          <li>
            <Code>package.json</Code> with appropriate dependencies
          </li>
          <li>
            <Code>tsconfig.json</Code> (for TypeScript projects)
          </li>
          <li>
            <Code>.vibe/project.json</Code> with build, dev, test, and install
            commands
          </li>
        </ul>
        <p>
          For subsequent features, the agent integrates with the existing project
          structure, following conventions established by earlier features.
        </p>
      </Section>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-lg font-semibold text-fg mb-3 pb-2 border-b border-border">
        {title}
      </h2>
      <div className="space-y-3 text-sm text-fg-muted leading-relaxed">{children}</div>
    </section>
  );
}

function SubSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mt-3">
      <h3 className="text-sm font-semibold text-fg mb-2">{title}</h3>
      <div className="space-y-2">{children}</div>
    </div>
  );
}

function Code({ children }: { children: React.ReactNode }) {
  return (
    <code className="px-1.5 py-0.5 bg-canvas-subtle border border-border rounded text-xs text-accent-emphasis">
      {children}
    </code>
  );
}

function CodeBlock({ children }: { children: React.ReactNode }) {
  return (
    <pre className="bg-canvas-inset border border-border rounded-lg p-4 text-xs text-fg overflow-x-auto">
      <code>{children}</code>
    </pre>
  );
}

function DefinitionList({ items }: { items: { term: string; definition: string }[] }) {
  return (
    <dl className="space-y-2">
      {items.map(({ term, definition }) => (
        <div key={term} className="flex gap-2 text-sm">
          <dt className="shrink-0 font-medium text-fg w-32">{term}</dt>
          <dd className="text-fg-muted">{definition}</dd>
        </div>
      ))}
    </dl>
  );
}
