/**
 * Agentic compile loop: vibe files → working code.
 *
 * Compilation pipeline:
 *   1. Topologically sort features by their Uses: dependency graph.
 *   2. For each feature (in dependency order):
 *      a. Agentic generation (strong model) — explore workspace, generate code with tools.
 *      b. Agentic validation (fast model) — build, typecheck, test, fix errors.
 *   3. Accumulated code from upstream features flows into downstream context,
 *      so later features can import types/functions generated by earlier ones.
 *
 * Model tiering:
 *   AGENT_MODEL      — strong model for code generation (default: claude-sonnet-4-6)
 *   AGENT_FAST_MODEL — fast model for validation/fixing (default: same as AGENT_MODEL)
 *
 * Examples:
 *   AGENT_MODEL=claude-sonnet-4-6 AGENT_FAST_MODEL=claude-haiku-4-5-20251001
 *   AGENT_MODEL=gemini-2.5-flash  (both tiers use same model)
 */

import Anthropic from '@anthropic-ai/sdk';
import { GoogleGenerativeAI } from '@google/generative-ai';
import type { Content } from '@google/generative-ai';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execSync } from 'node:child_process';
import { parseVibeGrammar, buildDependencyGraph, fromGrammarName } from './vibeGrammar.ts';

// ─── Model tiering ──────────────────────────────────────────────────────────
const DEFAULT_GENERATION_MODEL = process.env.AGENT_MODEL ?? 'claude-sonnet-4-6';
const DEFAULT_VALIDATION_MODEL = process.env.AGENT_FAST_MODEL ?? DEFAULT_GENERATION_MODEL;

/** Per-job model configuration, resolved from user preferences. */
export interface ModelConfig {
  /** Generation model ID (e.g. 'claude-sonnet-4-6', 'gemini-2.5-flash'). */
  generationModel: string;
  /** Validation model ID. Defaults to generationModel if omitted. */
  validationModel?: string;
  /** Decrypted API key to use instead of env vars. */
  apiKey?: string;
  /** Provider hint — used to route the API key to the right client. */
  provider?: string;
}

const PHASE1_MAX_ITERATIONS = 10;
const PHASE2_MAX_ITERATIONS = 25;
const COMMAND_TIMEOUT_MS = 120_000;
const MAX_TOKENS = 32_768;
const THINKING_BUDGET = 10_000;
const COMPILE_BUDGET_MS = 12 * 60 * 1000; // 12 minutes wall-clock (leaves 3min buffer before 15min timeout)

const ALLOWED_COMMAND_PREFIXES = [
  'tsc', 'npx tsc', 'npx eslint', 'node', 'npm test', 'npm run', 'npx jest',
  'npx vitest', 'npx prettier', 'cat', 'ls', 'find', 'head', 'tail', 'wc',
];

export interface CodeFile {
  path: string;
  content: string;
}

// ─── Progress events ────────────────────────────────────────────────────────

export type CompileEvent =
  | { type: 'ideation_start'; description: string }
  | { type: 'ideation_done'; featureCount: number; features: string[] }
  | { type: 'compile_start'; features: string[]; order: string[]; generationModel: string; validationModel: string }
  | { type: 'feature_start'; slug: string; index: number; total: number }
  | { type: 'phase1_start'; slug: string }
  | { type: 'phase1_tool'; slug: string; tool: string; detail: string }
  | { type: 'phase1_done'; slug: string; fileCount: number }
  | { type: 'phase2_start'; slug: string }
  | { type: 'phase2_iteration'; slug: string; iteration: number; tools: string[] }
  | { type: 'phase2_done'; slug: string; fileCount: number }
  | { type: 'feature_done'; slug: string; fileCount: number }
  | { type: 'compile_done'; totalFiles: number; features: number };

export type OnProgress = (event: CompileEvent) => void;

const noopProgress: OnProgress = () => {};

// ─── System prompts ─────────────────────────────────────────────────────────

const GENERATION_SYSTEM_PROMPT = `You are an expert software engineer generating code from a Vibe specification inside a sandboxed workspace.

## How to work
1. **Explore first.** Use list_files to see the workspace structure. If upstream code exists, read key files to understand conventions, types, and patterns already established.
2. **Plan your approach.** Think about what files you need to create, what types to define, how to structure the code, and how it integrates with existing files.
3. **Generate file by file.** Use write_file to create each implementation file. Write complete, production-quality code — no stubs or placeholders.
4. **Follow existing conventions.** If upstream code uses specific patterns (e.g. barrel exports, specific directory structure, naming conventions), follow them.
5. **Import, don't redefine.** If a type, function, or constant exists in an upstream file, import it. Never redefine something that already exists.
6. **Call finish when done.** Once all implementation files are written, call finish.

## What to generate
- All source files needed to implement the feature spec
- Type definitions for any new domain entities
- If this is the FIRST feature, also generate: package.json, tsconfig.json, and .vibe/project.json
- If this is NOT the first feature, integrate with the existing project structure

## What NOT to generate
- Tests (those are for the validation phase)
- Unnecessary abstraction layers
- Configuration files that already exist in the workspace`;

const VALIDATION_SYSTEM_PROMPT = `You are an expert software engineer validating and fixing code inside a sandboxed workspace.

## Your capabilities
You have tools to read files, write files, edit files (apply targeted patches), list directory contents, search for patterns across files, and run shell commands. Use them methodically.

## How to work
1. **Understand first.** Read the project configuration (.vibe/project.json, package.json, tsconfig.json) and understand the project structure using list_files.
2. **Build incrementally.** Install dependencies, then build/typecheck, then run tests. Fix issues one at a time.
3. **Diagnose before fixing.** When you see an error, trace it to its root cause. Read the relevant files, search for related symbols. Don't guess.
4. **Use search_files liberally.** When you see an undefined import or unknown symbol, search for it.
5. **Use edit_file for small changes.** For fixing imports or type errors, patch just the affected lines instead of rewriting entire files.
6. **Test your fixes.** After writing a fix, re-run the failing command to verify it works.
7. **Know when to stop.** Call finish once the project builds without errors AND tests pass (or no tests exist).

## Integration context
You may be validating one feature in a multi-feature project. Code from previously compiled features is already in the workspace. Don't modify upstream files unless absolutely necessary.

## Common patterns
- Missing module: search for the export, check the import path, check tsconfig paths.
- Type error: read the type definition, understand expected vs provided.
- Test failure: read the test, understand the assertion, fix the implementation (not the test).

## What NOT to do
- Don't over-engineer or add unnecessary abstractions.
- Don't add dependencies that weren't in the original generation.
- Don't modify test files to make them pass — fix the implementation.
- Don't call finish until the build is clean.`;

// ─── Ideation prompt ─────────────────────────────────────────────────────────

const IDEATION_SYSTEM_PROMPT = `You are an expert software architect who decomposes high-level product descriptions into well-structured Vibe feature specs.

## Your task
Given a product description (and optionally a framework preference), output a set of \`.vibe/features/*.md\` files that fully cover the described product.

## Vibe spec format
Each feature spec is a markdown file with YAML frontmatter:

\`\`\`markdown
---
Uses: [DependencyFeature]
Data: [Entity1, Entity2]
Never:
  - Hard constraint
---

# Feature Title

Description of what this feature does and how it works.

## Key behaviors
- Behavior 1
- Behavior 2

## UI / API surface
- Endpoint or page description
\`\`\`

## Rules
1. **PascalCase names** for Uses/Data references (e.g., UserAuthentication, not user-authentication)
2. **Slug file names** use kebab-case (e.g., \`user-authentication.md\`)
3. **Uses:** declares dependencies on other features you're creating. Order matters — a feature can only depend on features that would logically exist independently.
4. **Data:** declares domain entities this feature introduces or touches
5. **Never:** hard constraints the AI compiler must respect
6. **Be specific** — include enough detail that a developer (or AI) could implement each feature without guessing
7. **Decompose thoughtfully** — each feature should be a cohesive unit. Don't make features too granular (1 endpoint) or too broad (entire app).
8. **3-7 features** is typical for a medium-complexity app

## Output format
Call the \`create_feature\` tool once for each feature you want to create. The slug becomes the filename (e.g., slug "user-auth" → \`.vibe/features/user-auth.md\`).
When you're done creating all features, call the \`finish\` tool.`;

// ─── Provider abstraction ──────────────────────────────────────────────────────

interface LLMProvider {
  readonly model: string;
  createMessage(
    system: string,
    messages: Anthropic.MessageParam[],
    tools: Anthropic.Tool[],
  ): Promise<{ content: Anthropic.ContentBlock[]; stop_reason: string }>;
}

// ── Anthropic provider ─────────────────────────────────────────────────────────

class AnthropicProvider implements LLMProvider {
  private readonly client: Anthropic;
  private readonly useThinking: boolean;
  readonly model: string;

  constructor(model: string, apiKey?: string) {
    this.model = model;
    this.useThinking = model.includes('sonnet') || model.includes('opus');
    this.client = apiKey ? new Anthropic({ apiKey }) : new Anthropic();
  }

  async createMessage(system: string, messages: Anthropic.MessageParam[], tools: Anthropic.Tool[]) {
    if (this.useThinking) {
      const res = await this.client.messages.create({
        model: this.model,
        max_tokens: MAX_TOKENS,
        system,
        thinking: { type: 'enabled', budget_tokens: THINKING_BUDGET },
        tools,
        messages,
      });
      const content = res.content.filter(
        (b) => b.type === 'text' || b.type === 'tool_use',
      ) as Anthropic.ContentBlock[];
      return { content, stop_reason: res.stop_reason ?? 'end_turn' };
    }

    const res = await this.client.messages.create({
      model: this.model,
      max_tokens: MAX_TOKENS,
      system,
      tools,
      messages,
    });
    return { content: res.content, stop_reason: res.stop_reason ?? 'end_turn' };
  }
}

// ── Gemini provider ────────────────────────────────────────────────────────────

class GeminiProvider implements LLMProvider {
  private readonly genAI: GoogleGenerativeAI;
  readonly model: string;

  constructor(model: string, apiKey?: string) {
    this.model = model;
    this.genAI = new GoogleGenerativeAI(apiKey ?? process.env.GEMINI_API_KEY ?? process.env.GOOGLE_API_KEY ?? '');
  }

  async createMessage(system: string, messages: Anthropic.MessageParam[], tools: Anthropic.Tool[]) {
    const idToName = new Map<string, string>();
    for (const msg of messages) {
      if (msg.role === 'assistant' && Array.isArray(msg.content)) {
        for (const block of msg.content) {
          if (block.type === 'tool_use') idToName.set(block.id, block.name);
        }
      }
    }

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const functionDeclarations: any[] = tools.map((t) => ({
      name: t.name,
      description: t.description ?? '',
      parameters: t.input_schema,
    }));

    const model = this.genAI.getGenerativeModel({
      model: this.model,
      systemInstruction: system,
      tools: [{ functionDeclarations }],
    });

    const contents: Content[] = toGeminiContents(messages, idToName);
    const result = await model.generateContent({ contents });
    const candidate = result.response.candidates?.[0];

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const content: any[] = [];
    for (const part of candidate?.content.parts ?? []) {
      if (part.text) {
        content.push({ type: 'text', text: part.text });
      } else if (part.functionCall) {
        content.push({
          type: 'tool_use',
          id: `gemini-${part.functionCall.name}-${Date.now()}`,
          name: part.functionCall.name,
          input: (part.functionCall.args as Record<string, unknown>) ?? {},
        });
      }
    }
    const typedContent = content as Anthropic.ContentBlock[];
    const hasCalls = typedContent.some((b) => b.type === 'tool_use');
    return { content: typedContent, stop_reason: hasCalls ? 'tool_use' : 'end_turn' };
  }
}

function toGeminiContents(
  messages: Anthropic.MessageParam[],
  idToName: Map<string, string>,
): Content[] {
  return messages.flatMap((msg): Content[] => {
    if (typeof msg.content === 'string') {
      return [{ role: msg.role === 'assistant' ? 'model' : 'user', parts: [{ text: msg.content }] }];
    }

    if (msg.role === 'user') {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const parts: any[] = [];
      for (const block of msg.content as Anthropic.ContentBlockParam[]) {
        if (!('type' in block)) continue;
        if (block.type === 'tool_result') {
          const name = idToName.get(block.tool_use_id) ?? block.tool_use_id;
          const resultText =
            typeof block.content === 'string'
              ? block.content
              : Array.isArray(block.content)
                ? block.content.map((b) => ('text' in b ? b.text : '')).join('')
                : '';
          parts.push({ functionResponse: { name, response: { result: resultText } } });
        } else if (block.type === 'text') {
          parts.push({ text: block.text });
        }
      }
      return parts.length > 0 ? [{ role: 'user', parts }] : [];
    }

    if (msg.role === 'assistant') {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const parts: any[] = [];
      for (const block of msg.content as Anthropic.ContentBlock[]) {
        if (block.type === 'text') {
          parts.push({ text: block.text });
        } else if (block.type === 'tool_use') {
          parts.push({ functionCall: { name: block.name, args: block.input as Record<string, unknown> } });
        }
      }
      return parts.length > 0 ? [{ role: 'model', parts }] : [];
    }

    return [];
  });
}

function createProvider(model: string, apiKey?: string): LLMProvider {
  return model.startsWith('gemini')
    ? new GeminiProvider(model, apiKey)
    : new AnthropicProvider(model, apiKey);
}

// ─── Topological sort ─────────────────────────────────────────────────────────

interface FeatureNode {
  slug: string;
  path: string;
  content: string;
}

function topologicalSort(features: FeatureNode[]): FeatureNode[] {
  const slugToFeature = new Map(features.map((f) => [f.slug, f]));
  const graph = buildDependencyGraph(
    features.map((f) => ({ slug: f.slug, content: f.content })),
  );

  const inDegree = new Map<string, number>();
  for (const f of features) inDegree.set(f.slug, 0);

  for (const [, deps] of graph) {
    for (const dep of deps) {
      if (inDegree.has(dep)) {
        inDegree.set(dep, (inDegree.get(dep) ?? 0) + 1);
      }
    }
  }

  const queue: string[] = [];
  for (const [slug, deg] of inDegree) {
    if (deg === 0) queue.push(slug);
  }

  const sorted: FeatureNode[] = [];
  const visited = new Set<string>();
  while (queue.length > 0) {
    const slug = queue.shift()!;
    if (visited.has(slug)) continue;
    visited.add(slug);

    const feature = slugToFeature.get(slug);
    if (feature) sorted.push(feature);

    for (const dep of graph.get(slug) ?? []) {
      if (!inDegree.has(dep)) continue;
      const newDeg = (inDegree.get(dep) ?? 1) - 1;
      inDegree.set(dep, newDeg);
      if (newDeg === 0) queue.push(dep);
    }
  }

  for (const f of features) {
    if (!visited.has(f.slug)) sorted.push(f);
  }

  return sorted;
}

// ─── Ideation: description → vibe features ─────────────────────────────────────

const IDEATION_TOOLS: Anthropic.Tool[] = [
  {
    name: 'create_feature',
    description: 'Create a vibe feature spec file. Call once per feature.',
    input_schema: {
      type: 'object' as const,
      properties: {
        slug: {
          type: 'string',
          description: 'Kebab-case filename slug (e.g. "user-authentication"). Becomes .vibe/features/<slug>.md',
        },
        content: {
          type: 'string',
          description: 'Full markdown content including YAML frontmatter (---\\nUses: [...]\\n...\\n---\\n# Title\\n...)',
        },
      },
      required: ['slug', 'content'],
    },
  },
  {
    name: 'finish',
    description: 'Call when all features have been created.',
    input_schema: { type: 'object' as const, properties: {} },
  },
];

/**
 * Use an LLM to decompose a natural-language description into vibe feature specs.
 */
async function ideateFeatures(
  provider: LLMProvider,
  description: string,
  framework: string | null | undefined,
  onProgress: OnProgress,
): Promise<CodeFile[]> {
  onProgress({ type: 'ideation_start', description });

  const userPrompt = [
    `## Product Description\n${description}`,
    framework ? `\n## Framework\nUse ${framework} as the primary framework.` : '',
    '\nDecompose this into vibe feature specs. Create each feature with the create_feature tool, then call finish.',
  ].join('');

  const messages: Anthropic.MessageParam[] = [{ role: 'user', content: userPrompt }];
  const features: CodeFile[] = [];

  for (let i = 0; i < PHASE1_MAX_ITERATIONS; i++) {
    const res = await provider.createMessage(IDEATION_SYSTEM_PROMPT, messages, IDEATION_TOOLS);

    // Collect assistant response
    messages.push({ role: 'assistant', content: res.content });

    const toolUses = res.content.filter((b): b is Anthropic.ToolUseBlock => b.type === 'tool_use');
    if (toolUses.length === 0) break; // model stopped calling tools

    const toolResults: Anthropic.ToolResultBlockParam[] = [];
    let finished = false;
    for (const tu of toolUses) {
      if (tu.name === 'finish') {
        finished = true;
        toolResults.push({ type: 'tool_result', tool_use_id: tu.id, content: 'Done.' });
      } else if (tu.name === 'create_feature') {
        const input = tu.input as { slug: string; content: string };
        const filePath = `.vibe/features/${input.slug}.md`;
        features.push({ path: filePath, content: input.content });
        toolResults.push({ type: 'tool_result', tool_use_id: tu.id, content: `Created ${filePath}` });
      }
    }
    messages.push({ role: 'user', content: toolResults });
    if (finished) break;
  }

  onProgress({
    type: 'ideation_done',
    featureCount: features.length,
    features: features.map((f) => f.path.replace(/^\.vibe\/features\//, '').replace(/\.md$/, '')),
  });

  return features;
}

// ─── Public API ────────────────────────────────────────────────────────────────

/**
 * Ideate vibe features from a description, then compile them into code.
 *
 * This is the full "description → vibes → code" pipeline used when a user
 * creates a project from a natural-language prompt without pre-existing features.
 *
 * @returns An object with both the generated vibe features and implementation code.
 */
export async function runIdeateAndCompile(
  description: string,
  framework: string | null | undefined,
  onProgress: OnProgress = noopProgress,
  modelConfig?: ModelConfig,
): Promise<{ vibeFeatures: CodeFile[]; code: CodeFile[] }> {
  const genModel = modelConfig?.generationModel ?? DEFAULT_GENERATION_MODEL;
  const apiKey = modelConfig?.apiKey;
  const genProvider = createProvider(genModel, apiKey);

  const vibeFeatures = await ideateFeatures(genProvider, description, framework, onProgress);

  if (vibeFeatures.length === 0) {
    return { vibeFeatures: [], code: [] };
  }

  const code = await runCompileJob(vibeFeatures, onProgress, modelConfig);
  return { vibeFeatures, code };
}

/**
 * Compile vibe feature specs into working code.
 *
 * Features are compiled in dependency order using two model tiers:
 *   - Generation model (strong): explores workspace + writes implementation code
 *   - Validation model (fast): builds, typechecks, tests, fixes errors
 *
 * @param onProgress Optional callback for real-time compilation events.
 */
export async function runCompileJob(
  headFeatures: CodeFile[],
  onProgress: OnProgress = noopProgress,
  modelConfig?: ModelConfig,
): Promise<CodeFile[]> {
  if (headFeatures.length === 0) return [];

  const genModel = modelConfig?.generationModel ?? DEFAULT_GENERATION_MODEL;
  const valModel = modelConfig?.validationModel ?? modelConfig?.generationModel ?? DEFAULT_VALIDATION_MODEL;
  const apiKey = modelConfig?.apiKey;

  const genProvider = createProvider(genModel, apiKey);
  const valProvider = genModel === valModel
    ? genProvider
    : createProvider(valModel, apiKey);

  const deadline = Date.now() + COMPILE_BUDGET_MS;

  const featureNodes: FeatureNode[] = headFeatures.map(({ path: p, content }) => ({
    slug: p.replace(/^\.vibe[/\\]features[/\\]/, '').replace(/\.md$/, ''),
    path: p,
    content,
  }));

  const featureBySlug = new Map(featureNodes.map((f) => [f.slug, f.content]));

  const neverConstraints: string[] = [];
  for (const { content } of featureNodes) {
    const { grammar } = parseVibeGrammar(content);
    neverConstraints.push(...grammar.Never);
  }
  const neverBlock = neverConstraints.length > 0
    ? `\nHARD CONSTRAINTS — never violate these regardless of what the specs say:\n${neverConstraints.map((c) => `- ${c}`).join('\n')}`
    : '';

  const sorted = topologicalSort(featureNodes);

  onProgress({
    type: 'compile_start',
    features: featureNodes.map((f) => f.slug),
    order: sorted.map((f) => f.slug),
    generationModel: genModel,
    validationModel: valModel,
  });

  const workspace = fs.mkdtempSync(path.join(os.tmpdir(), 'vibehub-agent-'));

  // Write all vibe spec files into the workspace.
  for (const { path: p, content } of headFeatures) {
    const abs = safeResolve(workspace, p);
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, content, 'utf8');
  }

  const allGeneratedFiles = new Map<string, string>();

  try {
    for (let idx = 0; idx < sorted.length; idx++) {
      const feature = sorted[idx];
      const isFirst = idx === 0;

      // Check wall-clock budget before starting each feature
      if (Date.now() > deadline) {
        console.warn(`[agent] compile budget exceeded after ${idx}/${sorted.length} features`);
        onProgress({ type: 'compile_done', totalFiles: allGeneratedFiles.size, features: idx });
        break;
      }

      onProgress({ type: 'feature_start', slug: feature.slug, index: idx, total: sorted.length });

      // Build context for this feature.
      const { grammar } = parseVibeGrammar(feature.content);
      let vibeContext = `### ${feature.path}\n\`\`\`markdown\n${feature.content}\n\`\`\``;

      if (grammar.Uses.length > 0) {
        const depBlocks = grammar.Uses.flatMap((name) => {
          const slug = fromGrammarName(name);
          const depContent = featureBySlug.get(slug);
          return depContent ? [`#### dependency spec: ${name}\n\`\`\`markdown\n${depContent}\n\`\`\``] : [];
        });
        if (depBlocks.length > 0) vibeContext += '\n\n' + depBlocks.join('\n\n');
      }

      const upstreamContext = buildUpstreamContext(allGeneratedFiles);

      // ── Phase 1: Agentic generation (strong model) ──
      onProgress({ type: 'phase1_start', slug: feature.slug });

      const generated = await agenticGenerate(
        genProvider, workspace, vibeContext, neverBlock, upstreamContext, isFirst, feature.slug, onProgress, deadline,
      );

      for (const { path: p, content } of generated) {
        allGeneratedFiles.set(p, content);
      }
      onProgress({ type: 'phase1_done', slug: feature.slug, fileCount: generated.length });

      // Check budget between phases
      if (Date.now() > deadline) {
        console.warn(`[agent] compile budget exceeded after phase 1 of ${feature.slug}`);
        onProgress({ type: 'feature_done', slug: feature.slug, fileCount: allGeneratedFiles.size });
        break;
      }

      // ── Phase 2: Agentic validation (fast model) ──
      onProgress({ type: 'phase2_start', slug: feature.slug });

      const validated = await validationLoop(
        valProvider, workspace, vibeContext, generated, neverBlock, upstreamContext, feature.slug, onProgress, deadline,
      );

      for (const { path: p, content } of validated) {
        allGeneratedFiles.set(p, content);
      }
      onProgress({ type: 'phase2_done', slug: feature.slug, fileCount: validated.length });

      onProgress({ type: 'feature_done', slug: feature.slug, fileCount: allGeneratedFiles.size });
    }

    onProgress({ type: 'compile_done', totalFiles: allGeneratedFiles.size, features: sorted.length });
    return [...allGeneratedFiles.entries()].map(([p, content]) => ({ path: p, content }));
  } finally {
    fs.rmSync(workspace, { recursive: true, force: true });
  }
}

// ─── Upstream context builder ─────────────────────────────────────────────────

function buildUpstreamContext(generatedFiles: Map<string, string>): string {
  if (generatedFiles.size === 0) return '';

  const sections: string[] = [];
  for (const [filePath, content] of generatedFiles) {
    if (filePath.startsWith('.vibe/')) continue;
    const ext = path.extname(filePath);
    if (!['.ts', '.tsx', '.js', '.jsx', '.py', '.go', '.rs'].includes(ext)) continue;

    const header = extractCodeHeader(content, ext);
    if (header) {
      sections.push(`### ${filePath}\n\`\`\`\n${header}\n\`\`\``);
    }
  }

  if (sections.length === 0) return '';
  return `\n## Code already generated by upstream features\nThese files exist in the workspace. Import from them — do NOT redefine their types or functions.\n\n${sections.join('\n\n')}`;
}

function extractCodeHeader(content: string, ext: string): string {
  const lines = content.split('\n');
  const headerLines: string[] = [];
  const maxLines = 80;

  if (['.ts', '.tsx', '.js', '.jsx'].includes(ext)) {
    let inBlock = false;
    let braceDepth = 0;

    for (const line of lines) {
      if (headerLines.length >= maxLines) break;
      const trimmed = line.trim();
      if (
        trimmed.startsWith('import ') ||
        trimmed.startsWith('export ') ||
        trimmed.startsWith('interface ') ||
        trimmed.startsWith('type ') ||
        trimmed.startsWith('enum ') ||
        (trimmed.startsWith('const ') && trimmed.includes('=') && !trimmed.includes('=>')) ||
        trimmed.startsWith('class ') ||
        trimmed.startsWith('function ') ||
        trimmed.startsWith('async function ')
      ) {
        headerLines.push(line);
        if (trimmed.includes('{') && !trimmed.includes('}')) {
          inBlock = true;
          braceDepth = 1;
        }
        continue;
      }
      if (inBlock) {
        headerLines.push(line);
        for (const ch of trimmed) {
          if (ch === '{') braceDepth++;
          if (ch === '}') braceDepth--;
        }
        if (braceDepth <= 0) inBlock = false;
      }
    }
  } else if (ext === '.py') {
    for (const line of lines) {
      if (headerLines.length >= maxLines) break;
      const trimmed = line.trim();
      if (
        trimmed.startsWith('import ') || trimmed.startsWith('from ') ||
        trimmed.startsWith('class ') || trimmed.startsWith('def ') ||
        trimmed.startsWith('async def ') || trimmed.startsWith('@')
      ) {
        headerLines.push(line);
      }
    }
  } else if (ext === '.go') {
    for (const line of lines) {
      if (headerLines.length >= maxLines) break;
      const trimmed = line.trim();
      if (
        trimmed.startsWith('package ') || trimmed.startsWith('import ') ||
        trimmed.startsWith('type ') || trimmed.startsWith('func ') ||
        trimmed.startsWith('var ') || trimmed.startsWith('const ')
      ) {
        headerLines.push(line);
      }
    }
  } else {
    return lines.slice(0, 40).join('\n');
  }

  return headerLines.join('\n');
}

// ─── Phase 1: Agentic generation ─────────────────────────────────────────────

/** Tools available during generation — no run_command or edit_file. */
const GENERATION_TOOLS: Anthropic.Tool[] = [
  {
    name: 'write_file',
    description: 'Create or overwrite a file in the workspace. Always write COMPLETE file content.',
    input_schema: {
      type: 'object' as const,
      properties: {
        path: { type: 'string', description: 'Relative file path.' },
        content: { type: 'string', description: 'Full file content.' },
      },
      required: ['path', 'content'],
    },
  },
  {
    name: 'read_file',
    description: 'Read a file from the workspace.',
    input_schema: {
      type: 'object' as const,
      properties: {
        path: { type: 'string', description: 'Relative file path.' },
      },
      required: ['path'],
    },
  },
  {
    name: 'list_files',
    description: 'List files and directories. Use to discover workspace structure and existing code.',
    input_schema: {
      type: 'object' as const,
      properties: {
        directory: { type: 'string', description: 'Directory to list. Defaults to "." (root).' },
        pattern: { type: 'string', description: 'Glob pattern to filter (e.g. "**/*.ts").' },
        max_depth: { type: 'number', description: 'Max recursion depth. Defaults to 10.' },
      },
      required: [],
    },
  },
  {
    name: 'search_files',
    description: 'Search for a regex pattern across workspace files. Find exports, types, imports, etc.',
    input_schema: {
      type: 'object' as const,
      properties: {
        pattern: { type: 'string', description: 'Regex pattern to search for.' },
        directory: { type: 'string', description: 'Directory to search. Defaults to ".".' },
        file_pattern: { type: 'string', description: 'Glob filter for files (e.g. "*.ts").' },
        max_results: { type: 'number', description: 'Max results. Defaults to 50.' },
      },
      required: ['pattern'],
    },
  },
  {
    name: 'finish',
    description: 'Signal that all implementation files have been written. Call this when generation is complete.',
    input_schema: {
      type: 'object' as const,
      properties: {
        summary: { type: 'string', description: 'Brief summary of files generated.' },
      },
      required: [],
    },
  },
];

async function agenticGenerate(
  provider: LLMProvider,
  workspace: string,
  vibeContext: string,
  neverBlock: string,
  upstreamContext: string,
  isFirstFeature: boolean,
  slug: string,
  onProgress: OnProgress,
  deadline: number,
): Promise<CodeFile[]> {
  const writtenFiles = new Map<string, string>();

  const projectJsonNote = isFirstFeature
    ? `\nThis is the FIRST feature. Generate project scaffolding too:
- package.json with appropriate dependencies
- tsconfig.json if TypeScript
- .vibe/project.json: {"language":"...","framework":"...","install":"...","dev":"...","build":"...","test":"..."}\n`
    : `\nThis is NOT the first feature. A project structure already exists in the workspace. Integrate with it.\n`;

  const upstreamNote = upstreamContext
    ? `\n${upstreamContext}\n\nImport from existing files — do NOT redefine their types or functions.\n`
    : '';

  const messages: Anthropic.MessageParam[] = [
    {
      role: 'user',
      content: `Generate the implementation for this feature.
${neverBlock}
${projectJsonNote}${upstreamNote}
## Vibe Specification

${vibeContext}

Start by exploring the workspace with list_files to understand what already exists, then generate your implementation files.`,
    },
  ];

  for (let i = 0; i < PHASE1_MAX_ITERATIONS; i++) {
    if (Date.now() > deadline) break;

    const response = await provider.createMessage(GENERATION_SYSTEM_PROMPT, messages, GENERATION_TOOLS);
    messages.push({ role: 'assistant', content: response.content });

    if (response.stop_reason === 'end_turn') break;

    const toolResults: Anthropic.ToolResultBlockParam[] = [];
    let finished = false;

    for (const block of response.content) {
      if (block.type !== 'tool_use') continue;

      let result: string;
      try {
        switch (block.name) {
          case 'write_file': {
            const { path: filePath, content } = block.input as { path: string; content: string };
            const abs = safeResolve(workspace, filePath);
            fs.mkdirSync(path.dirname(abs), { recursive: true });
            fs.writeFileSync(abs, content, 'utf8');
            writtenFiles.set(filePath, content);
            onProgress({ type: 'phase1_tool', slug, tool: 'write_file', detail: filePath });
            result = `Written: ${filePath} (${content.length} bytes)`;
            break;
          }
          case 'read_file': {
            const { path: filePath } = block.input as { path: string };
            result = readFileImpl(workspace, filePath);
            break;
          }
          case 'list_files': {
            const input = block.input as { directory?: string; pattern?: string; max_depth?: number };
            result = listFiles(workspace, input.directory ?? '.', input.pattern, input.max_depth ?? 10);
            break;
          }
          case 'search_files': {
            const input = block.input as { pattern: string; directory?: string; file_pattern?: string; max_results?: number };
            result = searchFiles(workspace, input.pattern, input.directory ?? '.', input.file_pattern, input.max_results ?? 50);
            break;
          }
          case 'finish': {
            finished = true;
            result = 'Generation complete.';
            break;
          }
          default:
            result = `Unknown tool: ${block.name}`;
        }
      } catch (err) {
        result = `Error: ${err instanceof Error ? err.message : String(err)}`;
      }

      toolResults.push({ type: 'tool_result', tool_use_id: block.id, content: result });
    }

    messages.push({ role: 'user', content: toolResults });
    if (finished) break;
  }

  return readTrackedFiles(workspace, writtenFiles);
}

// ─── Phase 2: Agentic validation ─────────────────────────────────────────────

const VALIDATION_TOOLS: Anthropic.Tool[] = [
  {
    name: 'write_file',
    description: 'Write or overwrite a file. Always write COMPLETE content — no placeholders.',
    input_schema: {
      type: 'object' as const,
      properties: {
        path: { type: 'string', description: 'Relative file path.' },
        content: { type: 'string', description: 'Full file content.' },
      },
      required: ['path', 'content'],
    },
  },
  {
    name: 'edit_file',
    description:
      'Apply a targeted edit by replacing a specific string. More efficient than write_file for small fixes. ' +
      'The old_string must match exactly one location in the file.',
    input_schema: {
      type: 'object' as const,
      properties: {
        path: { type: 'string', description: 'Relative file path.' },
        old_string: { type: 'string', description: 'Exact string to find (must be unique in the file).' },
        new_string: { type: 'string', description: 'Replacement string.' },
      },
      required: ['path', 'old_string', 'new_string'],
    },
  },
  {
    name: 'read_file',
    description: 'Read a file from the workspace.',
    input_schema: {
      type: 'object' as const,
      properties: {
        path: { type: 'string', description: 'Relative file path.' },
      },
      required: ['path'],
    },
  },
  {
    name: 'list_files',
    description: 'List files and directories. Supports glob patterns.',
    input_schema: {
      type: 'object' as const,
      properties: {
        directory: { type: 'string', description: 'Directory to list. Defaults to ".".' },
        pattern: { type: 'string', description: 'Glob pattern to filter.' },
        max_depth: { type: 'number', description: 'Max depth. Defaults to 10.' },
      },
      required: [],
    },
  },
  {
    name: 'search_files',
    description: 'Regex search across files. Find imports, types, exports, etc.',
    input_schema: {
      type: 'object' as const,
      properties: {
        pattern: { type: 'string', description: 'Regex pattern.' },
        directory: { type: 'string', description: 'Directory. Defaults to ".".' },
        file_pattern: { type: 'string', description: 'File glob filter.' },
        max_results: { type: 'number', description: 'Max results. Defaults to 50.' },
      },
      required: ['pattern'],
    },
  },
  {
    name: 'run_command',
    description:
      'Run a shell command (npm install, npx tsc --noEmit, npm test, etc.). ' +
      'Timeout: 120s. Returns stdout + stderr.',
    input_schema: {
      type: 'object' as const,
      properties: {
        command: { type: 'string', description: 'Shell command to run.' },
      },
      required: ['command'],
    },
  },
  {
    name: 'finish',
    description:
      'Signal validation is complete. Call ONLY after build succeeds and tests pass.',
    input_schema: {
      type: 'object' as const,
      properties: {
        summary: { type: 'string', description: 'Summary of validation and fixes applied.' },
      },
      required: [],
    },
  },
];

async function validationLoop(
  provider: LLMProvider,
  workspace: string,
  vibeContext: string,
  generatedFiles: CodeFile[],
  neverBlock: string,
  upstreamContext: string,
  slug: string,
  onProgress: OnProgress,
  deadline: number,
): Promise<CodeFile[]> {
  const writtenFiles = new Map<string, string>(
    generatedFiles.map(({ path: p, content }) => [p, content]),
  );

  const fileListing = generatedFiles.map((f) => `  - ${f.path}`).join('\n');
  const upstreamNote = upstreamContext
    ? `\n${upstreamContext}\n\nUpstream code is in the workspace. Integrate with it.\n`
    : '';

  const messages: Anthropic.MessageParam[] = [
    {
      role: 'user',
      content: `${neverBlock}

## Feature spec being validated
${vibeContext}
${upstreamNote}
## Files generated for this feature
${fileListing}

Validate this implementation:
1. list_files to see the workspace.
2. Read .vibe/project.json for build/test commands.
3. npm install (if needed).
4. Build/typecheck.
5. Fix errors: read files, search_files, edit_file/write_file, re-run.
6. Run tests. Fix failures.
7. finish when clean.`,
    },
  ];

  for (let i = 0; i < PHASE2_MAX_ITERATIONS; i++) {
    if (Date.now() > deadline) break;

    const response = await provider.createMessage(VALIDATION_SYSTEM_PROMPT, messages, VALIDATION_TOOLS);
    messages.push({ role: 'assistant', content: response.content });

    if (response.stop_reason === 'end_turn') break;

    const toolResults: Anthropic.ToolResultBlockParam[] = [];
    let finished = false;
    const iterationTools: string[] = [];

    for (const block of response.content) {
      if (block.type !== 'tool_use') continue;
      iterationTools.push(block.name);

      let result: string;
      try {
        switch (block.name) {
          case 'write_file': {
            const { path: filePath, content } = block.input as { path: string; content: string };
            const abs = safeResolve(workspace, filePath);
            fs.mkdirSync(path.dirname(abs), { recursive: true });
            fs.writeFileSync(abs, content, 'utf8');
            writtenFiles.set(filePath, content);
            result = `Written: ${filePath} (${content.length} bytes)`;
            break;
          }
          case 'edit_file': {
            const { path: filePath, old_string, new_string } = block.input as {
              path: string; old_string: string; new_string: string;
            };
            const abs = safeResolve(workspace, filePath);
            if (!fs.existsSync(abs)) {
              result = `Error: File not found: ${filePath}`;
            } else {
              const content = fs.readFileSync(abs, 'utf8');
              const occurrences = content.split(old_string).length - 1;
              if (occurrences === 0) {
                result = `Error: old_string not found in ${filePath}. Read the file first to get the exact text.`;
              } else if (occurrences > 1) {
                result = `Error: old_string matches ${occurrences} locations in ${filePath}. Provide more context to make it unique.`;
              } else {
                const updated = content.replace(old_string, new_string);
                fs.writeFileSync(abs, updated, 'utf8');
                writtenFiles.set(filePath, updated);
                result = `Edited: ${filePath}`;
              }
            }
            break;
          }
          case 'read_file': {
            const { path: filePath } = block.input as { path: string };
            result = readFileImpl(workspace, filePath);
            break;
          }
          case 'list_files': {
            const input = block.input as { directory?: string; pattern?: string; max_depth?: number };
            result = listFiles(workspace, input.directory ?? '.', input.pattern, input.max_depth ?? 10);
            break;
          }
          case 'search_files': {
            const input = block.input as { pattern: string; directory?: string; file_pattern?: string; max_results?: number };
            result = searchFiles(workspace, input.pattern, input.directory ?? '.', input.file_pattern, input.max_results ?? 50);
            break;
          }
          case 'run_command': {
            const { command } = block.input as { command: string };
            result = runSandboxedCommand(command, workspace);
            break;
          }
          case 'finish': {
            finished = true;
            result = 'Validation complete.';
            break;
          }
          default:
            result = `Unknown tool: ${block.name}`;
        }
      } catch (err) {
        result = `Error: ${err instanceof Error ? err.message : String(err)}`;
      }

      toolResults.push({ type: 'tool_result', tool_use_id: block.id, content: result });
    }

    onProgress({ type: 'phase2_iteration', slug, iteration: i + 1, tools: iterationTools });
    messages.push({ role: 'user', content: toolResults });

    if (finished) {
      return readTrackedFiles(workspace, writtenFiles);
    }
  }

  return readTrackedFiles(workspace, writtenFiles);
}

// ─── Tool implementations ────────────────────────────────────────────────────

function readFileImpl(workspace: string, filePath: string): string {
  const abs = safeResolve(workspace, filePath);
  if (!fs.existsSync(abs)) return `Error: File not found: ${filePath}`;
  const content = fs.readFileSync(abs, 'utf8');
  if (content.length > 50_000) {
    return content.slice(0, 50_000) + `\n\n… [truncated, ${content.length} total bytes]`;
  }
  return content;
}

function listFiles(workspace: string, directory: string, pattern?: string, maxDepth = 10): string {
  const base = safeResolve(workspace, directory);
  if (!fs.existsSync(base)) return `Error: Directory not found: ${directory}`;

  const results: string[] = [];
  const skipDirs = new Set(['node_modules', '.git', 'dist', '.next', 'coverage', '.turbo']);

  function walk(dir: string, depth: number) {
    if (depth > maxDepth || results.length >= 500) return;
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      if (entry.isDirectory() && skipDirs.has(entry.name)) continue;
      const full = path.join(dir, entry.name);
      const rel = path.relative(workspace, full);

      if (entry.isDirectory()) {
        results.push(rel + '/');
        walk(full, depth + 1);
      } else {
        if (pattern) {
          if (matchGlob(rel, pattern) || matchGlob(entry.name, pattern)) {
            results.push(rel);
          }
        } else {
          results.push(rel);
        }
      }
    }
  }

  walk(base, 0);
  if (results.length === 0) return pattern ? `No files matching "${pattern}" in ${directory}` : `Empty directory: ${directory}`;
  if (results.length >= 500) results.push(`… (truncated, 500+ entries)`);
  return results.join('\n');
}

function matchGlob(filepath: string, pattern: string): boolean {
  const regexStr = pattern
    .replace(/\./g, '\\.')
    .replace(/\*\*/g, '{{DOUBLESTAR}}')
    .replace(/\*/g, '[^/]*')
    .replace(/\?/g, '[^/]')
    .replace(/\{\{DOUBLESTAR\}\}/g, '.*');
  return new RegExp(`^${regexStr}$`).test(filepath);
}

function searchFiles(
  workspace: string,
  pattern: string,
  directory: string,
  filePattern?: string,
  maxResults = 50,
): string {
  const base = safeResolve(workspace, directory);
  if (!fs.existsSync(base)) return `Error: Directory not found: ${directory}`;

  let regex: RegExp;
  try {
    regex = new RegExp(pattern, 'i');
  } catch (e) {
    return `Error: Invalid regex: ${e instanceof Error ? e.message : String(e)}`;
  }

  const results: string[] = [];
  const skipDirs = new Set(['node_modules', '.git', 'dist', '.next', 'coverage', '.turbo']);
  const textExts = new Set([
    '.ts', '.tsx', '.js', '.jsx', '.json', '.md', '.yaml', '.yml',
    '.toml', '.css', '.scss', '.html', '.py', '.go', '.rs', '.java',
    '.rb', '.php', '.vue', '.svelte', '.sql', '.graphql', '.prisma',
    '.sh', '.bash', '.txt', '.env', '.cfg', '.ini', '.xml',
  ]);

  function walk(dir: string) {
    if (results.length >= maxResults) return;
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      if (results.length >= maxResults) return;
      if (entry.isDirectory()) {
        if (!skipDirs.has(entry.name)) walk(path.join(dir, entry.name));
        continue;
      }
      const ext = path.extname(entry.name).toLowerCase();
      if (!textExts.has(ext) && ext !== '') continue;
      if (filePattern && !matchGlob(entry.name, filePattern)) continue;

      const fullPath = path.join(dir, entry.name);
      const rel = path.relative(workspace, fullPath);
      let content: string;
      try {
        const stat = fs.statSync(fullPath);
        if (stat.size > 100_000) continue;
        content = fs.readFileSync(fullPath, 'utf8');
      } catch {
        continue;
      }

      const lines = content.split('\n');
      for (let i = 0; i < lines.length; i++) {
        if (results.length >= maxResults) break;
        if (regex.test(lines[i])) {
          results.push(`${rel}:${i + 1}: ${lines[i].trimEnd()}`);
        }
      }
    }
  }

  walk(base);
  if (results.length === 0) return `No matches for /${pattern}/ in ${directory}`;
  const header = results.length >= maxResults ? `(showing first ${maxResults} matches)\n` : '';
  return header + results.join('\n');
}

function readTrackedFiles(workspace: string, tracked: Map<string, string>): CodeFile[] {
  const files: CodeFile[] = [];
  for (const [filePath] of tracked) {
    const abs = path.resolve(workspace, filePath);
    try {
      const content = fs.readFileSync(abs, 'utf8');
      files.push({ path: filePath, content });
    } catch {
      // Deleted during loop — skip.
    }
  }
  return files;
}

// ─── Workspace helpers ─────────────────────────────────────────────────────────

function safeResolve(workspace: string, filePath: string): string {
  const abs = path.resolve(workspace, filePath);
  if (!abs.startsWith(workspace + path.sep) && abs !== workspace) {
    throw new Error(`Path traversal blocked: ${filePath}`);
  }
  return abs;
}

function runSandboxedCommand(command: string, workspace: string): string {
  const trimmed = command.trim();
  const allowed = ALLOWED_COMMAND_PREFIXES.some((prefix) => trimmed.startsWith(prefix));
  if (!allowed) {
    return (
      `Command not permitted: "${trimmed}". ` +
      `Allowed prefixes: ${ALLOWED_COMMAND_PREFIXES.join(', ')}.`
    );
  }
  try {
    const output = execSync(trimmed, {
      cwd: workspace,
      timeout: COMMAND_TIMEOUT_MS,
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'pipe'],
      maxBuffer: 1024 * 1024,
    });
    return output.trim() || '(no output — command succeeded)';
  } catch (err: unknown) {
    const e = err as { stdout?: string; stderr?: string; message?: string };
    const parts = [e.stdout, e.stderr].filter(Boolean).join('\n').trim();
    if (parts.length > 10_000) {
      return parts.slice(0, 10_000) + '\n\n… [output truncated]';
    }
    return parts || e.message || 'Command failed with no output.';
  }
}
